### ISSUE TITLE
scattering3d returns a tuple instead of tensor

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#158]
Each implementation has very different expectations of its inputs and outputs:
- 1D: Expects inputs of size `(B, 1, T)`, outputs `(B, P, T/2**J)`, where `P` is the number of scattering coefficients. Note that if the second dimension of the input is not `1`, it errors.
- 2D: Expects inputs of size `(B, C, M, N)`, outputs `(B, C, P, M/2**J, N/2**J)`. Note that the number of dimensions changes here between input and output (this may be desirable but is not consistent with 1D). Also, from what I understand, the second dimension here is essentially treated as a batch dimension.
- 3D: Expects inputs of size `(B, M, N, O)`, outputs a _tuple_ with elements of size `(B, ?, ?, ?)`. Not sure what's going on here.

We should think about harmonizing these to some extent.

**Comment by gexarcha** [comment]
The 3D version returns different outputs for different versions.

- "standard" would return `(B,P, M/2**J,N/2**J,O/2**J)` 
- "integral" would return `(B,P,1,1,1)` (or `(B,P)` not sure)
- "local" would return `(B,P,1)`

The reason for "integral" is practically dimensionality reduction (among others) because  3D  is typically large. For "local" you have to ask @louity to be certain but I think it's to identify interesting regions in the moduli (e.g. midpoints between bonded atoms in quantum chemistry)

**Comment by janden** [comment]
Cool. So can `integral` and `local` be computed from `standard`? The more we can standardize the function of the `forward()` functions, the better. It may be better to apply these transformations as post-processing, if possible.

Also, what's the purpose of the tuple structure? Is that necessary or could the Tensors be concatenated?

**Comment by gexarcha** [comment]
local probably not. Integral yes but it may be slower.

**Comment by gexarcha** [comment]
> Cool. So can `integral` and `local` be computed from `standard`? The more we can standardize the function of the `forward()` functions, the better. It may be better to apply these transformations as post-processing, if possible.
> 
> Also, what's the purpose of the tuple structure? Is that necessary or could the Tensors be concatenated?

Yes I can do that

**Comment by janden** [comment]
> local probably not.

Hmm ok. Maybe best to leave this right now. Is it something that's used anywhere else?

> Integral yes but it may be slower.

Slower because it would leave large arrays unaveraged? As long as they stay in GPU memory, is it that bad? The caller can always average them later, right?

> > Also, what's the purpose of the tuple structure? Is that necessary or could the Tensors be concatenated?
> 
> Yes I can do that

Ok. Let's do that, then.

**Comment by lostanlen** [comment]
FWIW "local" measures scattering transform near a single point, much in the same way as the foveal scattering of @AndreuxMath and @beedotkiran
So it makes sense that it does not have spatial coordinates
Likewise for integral
@janden we might consider implementing integral in 1d in the future, as it runs faster than convolution with phi

@gexarcha I think that there are two issues here. One is how to interface local and integral with standard. The other is the output type: tuple vs tensor. The former can be postponed to `v0.2`, but the output type issue needs to be resolved before we release `v0.1.0-alpha`.

**Comment by eickenberg** [comment]
(Woa I thought we had lost this issue somewhere, but it just has a new title :) )

I think we are probably in the luxurious situation where we can just operate on the last n relevant axes of our data, e.g. by reshaping everything else into one huge sample axis and then reshaping back after the operation is done.

It would accommodate batchnorm and all the other shape-bound issues that might come up, since we reshape back after. 

The only thing that might happen is that the initial reshape triggers a copy. But, most probably, if it did trigger a copy, then the GPU wouldn't  have been able to handle its ordering without making a copy anyway.

This relatively liberal input shape requirement has been the general practice I have done in code that I write, but I have gotten repeated feedback stating that it becomes hard to read (OK maybe at its most extreme it was, since it did 1D,2D,3D all in one). So we should watch out for that if we proceed this way.

In general this has the advantage of flexibility but the disadvantage of maybe doing unexpected stuff.

**Comment by lostanlen** [comment]
Regarding the relationship between ndims of input and ndims of output, it is true that it would be good to be more consistent. At the beginning I wanted to modify the output of `Scattering1D`, but upon second thought I think it's best to modify the input.
So that: `(B,T)` maps to `(B,P,T')`
just like in other modules.
Then in the future we can think about implementing something more generic, as @janden and @eickenberg suggested:
`(T,)` -> `(P,T')`
`(B,T)` -> `(B,P,T')`
`(B,C,T)`->`(B,C,P,T')`
and so forth.
I can open a PR for that.

**Comment by janden** [comment]
> I think we are probably in the luxurious situation where we can just operate on the last n relevant axes of our data, e.g. by reshaping everything else into one huge sample axis and then reshaping back after the operation is done.
>
> ...
>
> In general this has the advantage of flexibility but the disadvantage of maybe doing unexpected stuff.

Agreed. I don't think so, as long as we're clear about the behavior. At the end of the day, it's not terribly more "unexpected" than `torch.fft`.

**Comment by janden** [comment]
Also, while we're here, 3D doesn't compute the zeroth order. Can we add this in? Currently, there's another function `compute_integrals` which does this (`test_scattering3d.py` uses this to get the full transform and compare it with the stored data).

**Comment by lostanlen** [comment]
yes, 3-D should include the zeroth order.
This can be done in a unified API by defining a list `orders` (defaulting to `range(1+max_order)`) in the `Scattering*D` instantiated object.

Working on the tuple vs tensor inconsistency at the moment.
