### ISSUE TITLE
Typo in kymat.io 2D scattering example

### ISSUE THREAD

**Issue by ctralie** [kymatio/kymatio#211]
Hi all,
First of all, thank you so much for this library.  The scattering transform has turned out to be a great tool in some of my research recently, and it's great not to have to create ugly wrappers around Matlab scatnet.

When getting this setup, however, I noticed that the API has changed slightly, so that Scattering2D expects a tuple shape parameter, instead of two separate dimensions.  Just an FYI.
Many thanks,
Chris Tralie

**Comment by ctralie** [comment]
To be more specific, I believe the line
~~~~python
scattering = Scattering2D(32, 32, 2)
~~~~

should be replaced with
~~~~python
scattering = Scattering2D(shape=(32, 32), J=2)
~~~~

At least, that's what worked for me

**Comment by lostanlen** [comment]
Hello @ctralie, welcome to Kymatio.
We just changed this in PR #195, which closed issue #202.
The typos in the example were changed in PRs #205 and #206.

**Comment by ctralie** [comment]
Hi Vincent, sorry I missed the previous issues about this!  The typo is on

http://www.kymat.io/

**Comment by lostanlen** [comment]
Oh I see, the typo is on the website, not the docs. 
Yeah, we need to refresh the docs once more before alpha release.
We are in the midst of a pretty big refactoring of API so that will happen anyway.

But a call of the form
`scattering = Scattering2D(J=2, shape=(32, 32))`

will remain supported until at least version `0.2`, so it's here to stay.
