### ISSUE TITLE
Unexpected warning in 3D

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#223]
With python=3.6, pytorch=1.0, and installing from sources, then doing "pytest", I obtain the following warning:

```
==================================================================================================== warnings summary ====================================================================================================
kymatio/scattering3d/tests/test_scattering3d.py::test_solid_harmonic_scattering
  /Users/oyallon/anaconda/envs/kymatio/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering3d/filter_bank.py:162: RuntimeWarning: invalid value encountered in sqrt
  /Users/oyallon/anaconda/envs/kymatio/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering3d/utils.py:105: RuntimeWarning: invalid value encountered in sqrt

kymatio/scattering3d/tests/test_scattering3d.py::test_larger_scales
  /Users/oyallon/anaconda/envs/kymatio/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering3d/filter_bank.py:162: RuntimeWarning: invalid value encountered in sqrt
  /Users/oyallon/anaconda/envs/kymatio/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering3d/utils.py:105: RuntimeWarning: invalid value encountered in sqrt

kymatio/scattering3d/tests/test_scattering3d.py::test_scattering_methods
  /Users/oyallon/anaconda/envs/kymatio/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering3d/filter_bank.py:162: RuntimeWarning: invalid value encountered in sqrt

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================================= 29 passed, 5 warnings in 56.58 seconds =========================================================================================

```

Any suggestions?

**Comment by janden** [comment]
Yeah I see that one too sometimes. It's not always there, though. Must be version-dependent.

**Comment by janden** [comment]
Ok so this one's a little tricky. Looks like there's an underlying issue in the Intel SVM library that is triggered when you give `np.sqrt` an array of size greater than 8192 in single precision, where some elements are exactly zero. More information is found in [here](https://github.com/numpy/numpy/issues/11448) and [here](https://github.com/ContinuumIO/anaconda-issues/issues/9129).

The proposed workaround is to suppress the warning selectively before calling `np.sqrt`, while still checking for invalid (i.e., negative reals) values.

Also note that this only seems to happen for older Python versions. In `py37`, this warning doesn't come up. It seems that Intel has fixed the bug in the meantime, so this is probably due to a more recent MKL version being available.

**Comment by edouardoyallon** [comment]
I see. I guess it's better to ignore it then.
