### ISSUE TITLE
ENH README.md: install from source + install from pip

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#224]
Hi,

I think we should add two manners to install the software in the README(similarly to pytorch)

1. Via the sources.(this is currently not proposed)
2. Via "pip"

Let me know your thoughts about it!

Edouard

**Comment by lostanlen** [comment]
if there is a use case for installing from source while not in `develop` mode, sure, let's document it by adding it into the README. but let's not add too many different separate ways installations instructions if they are not recommended.

**Comment by edouardoyallon** [comment]
The interest is as follow: it permits to have a working dev version(with extra features, via the install from source) as well as a released version(pypi) ; I think it might make sens. Waiting for @eickenberg

**Comment by lostanlen** [comment]
I'm very reluctant to the idea of telling users to use the dev branch.

By definition, the dev branch is for developers, not users. If our "casual" (non-dev) users clone and compile from source without keeping the habit of pulling latest changes and recompiling every time the source tree is updated, they will end up conducting scientific experiments that are based on "nightly" versions of the code. This is a terrible toll on reproducibility and almost defeats the purpose of stable releases in the first place. And if, on the other hand, certain users keep the habit of pulling latest changes from the master branch, well, they're essentially developers now, so why shouldn't they install with `setup.py develop` rather than `setup.py install`?

**Comment by edouardoyallon** [comment]
Well, my understanding is that the master could include new features that will have been developed and could be available before release to new users. I had in mind to follow similar guidelines as https://github.com/pytorch/pytorch#installation

**Comment by lostanlen** [comment]
following our discussion on Slack, i will update this to clearly state the implications of installing from source.
ETA < 6 hours

**Comment by lostanlen** [comment]
See my PR https://github.com/edouardoyallon/kymatio/pull/1
