### ISSUE TITLE
RELEASE requirements?

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#242]
Hi,

When doing:

```
conda install pytorch torchvision -c pytorch
pip install -i https://test.pypi.org/simple/ kymatio
```

then cloning the corresponding release, and doing `pytest`, I have tons of errors that are evidences that none of the requirements.txt packages are installed. Actually, this makes me think we should have a pip for the GPU version(like `pip install kymatio-gpu`)?

https://github.com/kymatio/kymatio/blob/master/requirements.txt

**Comment by edouardoyallon** [comment]
Solved:

The good command was:

 pip install --extra-index-url https://test.pypi.org/pypi/ kymatio

I believe we should also add a kymatio-gpu repo to pypi.

**Comment by edouardoyallon** [comment]
OK, instead to create a kymatio-gpu, as the files do not change, I simply propose to switch in the README.md:

`pip install -r requirements_optional_cuda.txt
`

to

`pip install -r https://raw.githubusercontent.com/kymatio/kymatio/master/requirements_optional.txt`

**Comment by lostanlen** [comment]
I would be in favor of a  `pip install kymatio-gpu`, but I can see how that is a commitment to have two, rather than one, PyPI hosted mirrors.
Also, random idea but: couldn't we simplify 
`pip install -r https://raw.githubusercontent.com/kymatio/kymatio/master/requirements_optional.txt`
to just 

`pip install scikit-cuda cupy`
?

I know that this part of the README will need to be updated if our dependencies ever change, but updating a README is not a huge commitment, and there are only two dependencies. Whereas a long URL like `raw.githubusercontent.com/...` can be a little bit scary to the user, where in fact it's just about installing two widely used packages.

**Comment by janden** [comment]
> I would be in favor of a `pip install kymatio-gpu`, but I can see how that is a commitment to have two, rather than one, PyPI hosted mirrors.

Yeah I'd rather go that route as well. It's a little more work for us, but the users' lives would be so much simpler. The question is whether we'd want to go PyTorch all the way and have "kymatio" and "kymatio-cpu"?

**Comment by edouardoyallon** [comment]
"kymatio" and "kymatio-cpu" sound good. @eickenberg ?

**Comment by eickenberg** [comment]
Yeah so I am not getting the exact problem that is leading to these suggestions.

Could one of you rephrase it for me - I think I'm being a bit dense.

**Comment by janden** [comment]
I'm not completely sure, but I think the underlying issue is that the `pip install -r requirements.txt` route is not what happens when you do `pip install kymatio`. Instead, it uses whatever's specified in `setup.py`. I think that, since all the requirements/install stuff is in there (that is, `setup.py`) anyhow, it might make more sense to have two versions of that file, one for CPU and one for GPU. Those would effectively correspond to two different PyPI packages.

**Comment by eickenberg** [comment]
> Instead, it uses whatever's specified in setup.py
But isn't requirements.txt loaded into setup.py? Or does that still not work?

For me the thing that I'd like to avoid is the installation not running through because it couldn't install a dependency. In that case I would just remove the dependency. Pip is not a smart system and it is sometimes better to leave them out. When the code doesn't run because a package is missing, the user just runs another pip command and it's fine.

Our package simply does not have differences in code so signifiant between gpu versions and non-gpu versions that several pypi mirrors would be merited. Also, thinking into the future, I see this easily proliferating into `kymatio-tf`, `kymatio-torch`, etc, which I am really not a fan of.

**Comment by janden** [comment]
> > Instead, it uses whatever's specified in setup.py
> 
> But isn't requirements.txt loaded into setup.py? Or does that still not work?

I think the issue is that the requirements for GPU are not in there, so you have to do an extra step (`pip install -r requirements_optional_cuda.txt`). Might be nice to delegate all that to the `pip install kymatio` step.

> Our package simply does not have differences in code so signifiant between gpu versions and non-gpu versions that several pypi mirrors would be merited. Also, thinking into the future, I see this easily proliferating into `kymatio-tf`, `kymatio-torch`, etc, which I am really not a fan of.

Sure, it's a whole other can of worms. I can go either way.

**Comment by eickenberg** [comment]
People will either install `torch` or `torch-cpu`. This should suffice for us. `skcuda` and `cupy` can be installed separately.

There seems to be a thing called `--install-options` for pip that we might be able to exploit. But I think that could lead to confusion.

How about the following procedure: we publish `kymatio` with minimal and stable dependencies. If lots of complaints come in via the issue tracker, then we can always still split into e.g. `kymatio` and `kymatio-cpu` (and later maybe even into more pieces if this seems like a good plan)

**Comment by edouardoyallon** [comment]
ok. So I'll edit such that:

`pip install scikit-cuda cupy`

replaces the requirements_cuda.txt
