### ISSUE TITLE
DOC Illustrative figure

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#286]
Branched off from #269.

It would be good to have some sort of picture. This could be a general schematic of the scattering transform, or maybe pictures of wavelets in 1D, 2D, and 3D?

**Comment by lostanlen** [comment]
Yes, a figure would be great. I would prefer a schema of the scattering transform rather than simply pictures of wavelets, because Kymatio is more than a library for wavelet transforms.

This is the one I've been using for many years to describe 1-D scattering. I think Stéphane uses it too now.
If it weren't for the awful jet colormap ... and the Greek letters "gamma", "gamma-2" ... it would do the job.

[temporal_scattering_flowchart.pdf](https://github.com/kymatio/kymatio/files/2756834/temporal_scattering_flowchart.pdf)

**Comment by janden** [comment]
I like this one, and I think we ultimately want to go with something like this, but:

1) `jet` is awful, as you say,
2) it uses different notation, as you also say,
3) it's a little busy and needs to be cleaned up, and,
4) most importantly, it's for 1D.

I'm as much of a 1D partisan as the next guy, but the (unfortunate) fact is that most people who use scattering use it for 2D. Those people will be misled, if not confused, if the first thing they see is a bunch of waveforms. It may be more illustrative to do images for the front page.

**Comment by edouardoyallon** [comment]
Hey. This is a great image. I think displaying 2D wavelet transforms would be confusing as well. @janden @lostanlen let's include this somewhere? Need first to reduce the size of this pdf!

**Comment by janden** [comment]
@edouardoyallon So you want to stick with 1D? Ok. I still think we would need to remake the figure with the correct notation, etc. That way, we can also make sure that things are properly rasterized and avoid the huge size.

**Comment by edouardoyallon** [comment]
> @edouardoyallon So you want to stick with 1D? Ok. I still think we would need to remake the figure with the correct notation, etc. That way, we can also make sure that things are properly rasterized and avoid the huge size.

Sounds good!

**Comment by edouardoyallon** [comment]
@janden maybe it's a good idea to generate this figure now?

**Comment by edouardoyallon** [comment]
Close via #416
