### ISSUE TITLE
Sphinx gallery does not create thumbnails for all examples

### ISSUE THREAD

**Issue by emmanuelle** [kymatio/kymatio#478]
See for example https://www.kymat.io/gallery_2d/regularized_inverse_scattering_MNIST.html#sphx-glr-gallery-2d-regularized-inverse-scattering-mnist-py and various other examples: the figure is neither displayed on the example page, nor in the gallery of thumbnails. I believe this is because of the 
```
if __name__ == '__main__':
    main()
```
structure. Putting all the instructions inside the `main()` function at the top level of the file should solve the problem. I'm happy to make a PR with these changes if the devs here agree.

**Comment by edouardoyallon** [comment]
Hi, thanks for opening the issue and reporting it. Could you also let us
know which command you used with sphinx as well as the corresponding
version of sphinx and python that you use? Thanks.

**Comment by eickenberg** [comment]
Hi Emmanuelle,

thanks for pointing that out! Our examples should not have that structure
(a main function that encapsulates stuff and gets called from the protected
region of the script). So this is an oversight that should change in any
case. If it also fixes our problem of figures not displaying in
sphinx-gallery, all the better!

If you have the time to do a PR, that would be awesome. Otherwise I'm sure
we'll get to it during our sprint at the end of the month.

Thanks!

**Comment by edouardoyallon** [comment]
Hi, alright, I thought the issue was that some figures were unintentionally
not displayed. My understanding here is that a/ only files prefixed by «
plot_ » should be run (to avoid running long scripts..) which was an
arbitrary choice b/ the website hasn’t been updated for a while... and the
files do not match with github...
Feel free to PR in the branch v2... but the latter might not be free of
bugs yet: I can do it in 2 weeks. Thanks again for your help.

**Comment by eickenberg** [comment]
Indeed, there were some runtime considerations when naming the scripts
plot_ or not in order to make reasonable automatic deployment of docs
possible (which we have on our Todo list)

**Comment by edouardoyallon** [comment]
I guess we can close this issue?
