### ISSUE TITLE
Why are we calling scattering at every epoch?

### ISSUE THREAD

**Issue by gexarcha** [kymatio/kymatio#615]
Hi all,
Is there a reason for calling scattering at every epoch? 
https://github.com/kymatio/kymatio/blob/e0fc10057f5f8bb947068bc40afff8d3d3729052/examples/2d/cifar_resnet_torch.py#L123

Is it supposed to be faster than loading from disk or something?

**Comment by eickenberg** [comment]
For the train set it's because of data augmentation

https://github.com/kymatio/kymatio/blob/e0fc10057f5f8bb947068bc40afff8d3d3729052/examples/2d/cifar_resnet_torch.py#L182

For the test set it's not technically necessary, so yeah, it could be pre-computed. Question is how much speed you gain, since you are working on optimizing something that from the start only takes 1/6 of the time of an epoch. If you speed up by a factor 2, then you end up at 11/12 of the original speed.

**Comment by edouardoyallon** [comment]
So I believe this is solved! ;)
