### ISSUE TITLE
Logic behind `Modulus`?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#682]
I don't follow why there's a `+ 2*i` [here](https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/backend/torch_skcuda_backend.py#L86), making results dependent on position in array:

```python
z[i] = make_${dtype}2(normf(2, x + 2*i), 0);
```

**Comment by edouardoyallon** [comment]
it creates a complex array of 0, and moves by 2 position (real, imag) the pointer in order to fill in the real array woth |.|

**Comment by OverLordGoldDragon** [comment]
_Pointers_... thanks.

Is output's dim redundantly doubled for code simplicity?

**Comment by edouardoyallon** [comment]
Sort of. Let's say the former code we wrote wasn't really consistent on many points.

**Comment by OverLordGoldDragon** [comment]
Is there anything preventing using halved dims and just changing `C2C` -> `R2C` [here](https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/core/scattering1d.py#L113)? It also eliminates need for `real(U_1_m)`.

**Comment by edouardoyallon** [comment]
I think it would be more relevant if you check out the `dev` branch, which tries to polish these aspects https://github.com/kymatio/kymatio/blob/dev/kymatio/backend/torch_backend.py#L57

@szagoruyko wrote this cuda kernel at this time because torch wasn't really efficient at doing this opteration, this isn't the case anymore.

Furthermore, I don't think we will consider adding a feature based on the `master` branch.....

**Comment by edouardoyallon** [comment]
Hi @OverLordGoldDragon , if that sounds good to you, I think this should move to the new section "Discussion". Thus I close this issue, as issue should just be here to report issues with the software. Thanks!

**Comment by OverLordGoldDragon** [comment]
@edouardoyallon Right, sure - Github failed to notify your last reply for some reason.
