### ISSUE TITLE
Kymatio Scattering transform 1D get frequencies in Hertz

### ISSUE THREAD

**Issue by GenoSmart** [kymatio/kymatio#713]
I'm trying to classify 1D signals by their frequencies after Scattering transform using Kymatio. How can I get the central frequencies of the wavelets being computed in Hertz ? I have 202 signals, each signal length is 78120, sampling rate (Fs) is 7812 samples per second. I set the parameters of the Scattring1D like this:

```
T = 2**16 # closest power of 2 product
J = 12 
Q = 8

input_mat = input_mat[:,:T]
scat_obj = Scattering1D(J, T, Q)
output_mat = scat_obj(input_mat)
```
I got output mat in shape of 202,546,16 Now I want to figure out what is the frequencies in Hz of the 546 wavelets in the filter banks that were being used for the scattering coefficients computation I got for each signal.

```
I tried to use
meta = scat_obj.meta()
central_freqs = meta['xi']
```
But 'xi' is a vector of shape (546,2) and its values are between 0 to 1 and I want to get them in Hz using my sampling rate.

Thank U !

**Comment by lostanlen** [comment]
Hello @GenoSmart. Just multiply the values of `xi` by your sampling rate in Hertz and you'll get the value you want in Hertz.

**Comment by GenoSmart** [comment]
Thank u for answering.
What the values of the xi vector represent? Why they are between 0 to 1?

**Comment by lostanlen** [comment]
@GenoSmart `xi` is our mathematical notation for the center frequency of a wavelet. We store them between 0 and 1 because we don't know the sample rate of the signal that the user provided. The value `0.5` represents the Nyquist frequency, i.e., half the sampling frequency as per Shannon's theorem.
In discrete-time digital signal processing, it is customary to map the values of `xi` to the range `[0, 2*pi]` but we figured that this factor of `2*pi` could be skipped entirely for our computation, and would introduce unnecessary complexity when a human would read those values.

One last thing: note that, in most cases, they don't range between 0 and 1 but between 0 and 0.5 at most. This is because we assume that the input signal is real, and thus its Fourier transform is symmetric. In other words, we assume that the spectrum between `0.5` and `1` is the mirror of the spectrum between `0` and `0.5`. Thus, we only perform wavelet analysis over the `[0, 0.5]` range to avoid duplicating computations (and coefficients).

I hope this helps!

**Comment by GenoSmart** [comment]
It is helping a lot thank you. 
One last question, I couldn't understand exactly how the connection between xi vector and phi_f,psi1_f,psi2_f vectors. 
Are the values in xi vector is a concatenation of all the filter banks frequencies?

**Comment by OverLordGoldDragon** [comment]
```python
fs = 400  # hertz
freqs = [tuple(xi * fs) for xi in scat_obj.meta()['xi']]
```
Out:
```python
[(nan, nan),  # lowpass of `x`
 (187.02175310815787, nan),  # first first-order wavelet (no second-order)
 (179.09264433837063, nan),  # second first-order wavelet (no second-order)
...
 (187.02175310815787, 17.5),  # [first first-order wavelet] * [first second-order wavelet]
 (187.02175310815787, 8.75),  # [first first-order wavelet] * [second second-order wavelet]
...
```

**Comment by lostanlen** [comment]
>  One last question, I couldn't understand exactly how the connection between xi vector and phi_f,psi1_f,psi2_f vectors.

`phi_f` is a low-pass filter so its center frequency `xi` is equal to zero by definition. Therefore, we do not encode it explicitly in the `meta` data.
You can retrieve the center frequencies of both orders by following the advice of @OverLordGoldDragon above ☝🏻
