### ISSUE TITLE
Bad default: `average_fr=False` & `aligned=True`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#799]
All second-order coefficients, except spinned `j1_fr=0`, are oversampled, which drastically amplifies output size and overfitting. Arguably the worst configuration of all. We should either default to both `True` or both `False`.

Since there's still some confusion, another attempt at explaining: `aligned=True` is an oversampled `aligned=False`. Filterbank parameters are independent of `aligned`, so in this sense the "paths" are unaffected.

 - 1D convs: all configs are valid. We pack `n2, n1_fr, n1` along channels, where they "don't talk" (every learned convolution filter sees only one path)
 - 2D convs: all `out_3D=True` configs are valid
 - 3D convs: all `out_3D=True` configs are valid if `n2` is packed along channels (so convolve over `(n1_fr, n1, t)` with spins split), since `out_3D=True` always enforces `aligned=True` on per-`n2` basis
 - 4D convs: no configs are valid. Only here is `aligned=False` a dealbreaker.
 - "all configs" assumes `'resample'`, since `'recalibrate'` breaks actual path alignment.

#791 makes `average_fr=True` a close equivalent to `average_fr=False` on averting loss of information due to averaging up to a certain `F`, but that's for later.

@lostanlen @janden

**Comment by lostanlen** [comment]
> But CQT never oversamples, at least not entirely.

Here's an implementation that oversamples entirely:
https://ltfat.org/doc/wavelets/ufwt.html

> Any hop_size > 1 for any time-frequency transform will always alias (its modulus), but the extent of loss varies with transform and signal parameters

yes, and?

> What I'm talking here is pure, 100% oversampling (within Gaussian float), which the user can opt to do (manually or via oversampling_fr)

yes, as a non-default opt-in: `out_3D=True`, `average_fr=False`
this will be slow and high-dimensional so unwieldy for large-scale applications but it turns out convenient for visualizations.
just pick a time-frequency region and visualize its scale-rate response


> We didn't agree here, no - your position was aligned=True must always hold.

Under `out_3D=False`, i don't see a need for talking about `aligned`. There is nothing to be aligned, since we just output a 2-D matrix (path, time). This matrix has as few rows as possible: meaning, the frequency axis is unpadded after frequential scattering/averaging. There is no zero-padding as in `out_3D=True`. What would be the effect of `aligned` in your mind?

Under `out_3D=True`, i am still in favor of `aligned=True` since i have not yet seen a definition of what `aligned=False` does, and what are its parameters.

Last time we spoke, `aligned=False` returns a 3-D tensor with variables `(n2, n1, t)` in which `n2` alone indicates the second-order filter but `n1` alone does not indicate the first-order filter. One needs knowledge of both `n1` and `n2` to know the exact path of the coefficient `Sx[n2,n1,t]`. This choice formatting defeats the purpose of returning a 3-D tensor: the tuple `(n1, n2)` really should be raveled into a single index `n` and the mis-`aligned` tensor should be reshaped as a matrix `n`. I will change my position if you can explain what `n1` means, and what coefficients with common `n1` but different `n2` have in common.
