### ISSUE TITLE
Make NumPy the default frontend

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#868]
Since we promised earlier:

```
  /home/jenkins/workspace/kymatio_dev/kymatio/frontend/entry.py:20: DeprecationWarning: Torch frontend is currently the default, but NumPy will become the default in the next version.
    warnings.warn("Torch frontend is currently the default, but NumPy will become the default in the next"
```

**Comment by MuawizChaudhary** [comment]
This is a deep learning package and we should focus on that first and foremost. This is a promise we should recind. @eickenberg thoughts?

**Comment by lostanlen** [comment]
@MuawizChaudhary since you seem to feel strongly about it (#806), know that i can have it either way. I've expressed my views here: https://github.com/kymatio/kymatio/issues/806#issuecomment-1113966458
and i think that @janden's compromise of "How about not having a default at all?" is optimal for be, even though i hadn't considered this option in my comment.

I don't have a clear enough sense of what problem you're trying to solve here. I don't think that telling our Torch users to import `from kymatio.torch` rather than `from kymatio` will alienate them from us. But maybe i'm missing the point here, so i'll abstain. (i.e. i won't block any decision that comes out from the three of you)

**Comment by janden** [comment]
For the reasons mentioned in #806 (dependencies, ease of installation), I don't think it's a good idea to have a hard torch dependency. That being said, I agree that it's a little strange to have the default be NumPy. Hence my suggestion that we remove `kymatio.Scattering*d` completely. We could change the deprecation message to say this and postpone the removal to the next release.

**Comment by lostanlen** [comment]
@MuawizChaudhary thanks for your PR
