### ISSUE TITLE
JTFS 

### ISSUE THREAD

**Issue by cyrusvahidi** [kymatio/kymatio#974]

**Comment by cyrusvahidi** [comment]
In the implementation of JTFS, we introduced a new backend primitive named `swap_time_frequency`. This conveniently tranposes the time and frequency axes such that we can perform scattering along the frequency axis. However, Kymatio has implemented _contiguity_ checks (for reasons that I am unaware of) that are checked when performing complex modulus and other operators. 

JTFS torch currently hits a runtime error due to non-contiguous tensors that appear to be induced by `swap_time_frequency` before frequential scattering.

I opened PR #972 which simply forced the tensor returned by `swap_time_frequency` to be contiguous. This may be inefficient, since it clones the tensor.

This poses the following questions:

* why did we need contiguous tensors in the first place?
* can we copy the tensor and force contiguity? 
* is there a more efficient approach?

**Comment by lostanlen** [comment]
Many thanks for opening this issue

> why did we need contiguous tensors in the first place?
 
https://stackoverflow.com/questions/69840389/what-functions-or-modules-require-contiguous-input/
"it seems that view is the only function that explicitly causes an exception when a non-contiguous input is passed."
 
 It makes sense that our users would like to call `view` the scattering transform, so guaranteeing contiguity of the _output_ is the safest choice here. However, since we never call `view` in base code, my understanding is that it's fine if some _intermediate_ computation of Kymatio is non-contiguous. By that logic, the repeated contiguity checks in Kymatio primitives are unnecessary. And the contiguity enforcement in #972 might as well have appeared later in the processing pipeline. (on the subsampled unpadded array rather than the intermediate one)
 
 > can we copy the tensor and force contiguity?
 
 That's what #972 does.
 By definition, an in-place transpose breaks contiguity but allocates no memory. An out-of-place transpose respects contiguity but allocates memory. 

> is there a more efficient approach?

My view (pun intended) is that we can defer the contiguity checks/allocations to the latest stage of the transform instead of having them in `swap_timefrequency`. This should be more efficient than #972 while passing the current unit tests.

The implication of what i'm saying is that we'd have to say goodbye to the contiguity checks in backend primitives.

LMK what you think!

**Comment by cyrusvahidi** [comment]
Bon.

Do we agree that the next course of action is to remove contiguity checks, and add a check that the final output is contiguous?

**Comment by lostanlen** [comment]
Yes. This is a backwards compatible change (from the standpoint of frontends) so it can happen right now without deprecation.

**Comment by janden** [comment]
I know this comes a little late, but IIRC, the reason for contiguity checks has to do with calls to skcuda, which naturally requires contiguous inputs. So if we're not using that backend, it should be fine to skip contiguity.

**Comment by lostanlen** [comment]
What's the status with skcuda? Is it officially supported / deprecated / dropped? Do we test it?

**Comment by janden** [comment]
We test it in the Jenkins pipeline.

**Comment by janden** [comment]
Looks like everything's good: https://app.codecov.io/gh/kymatio/kymatio/blob/main/kymatio/backend/torch_skcuda_backend.py

**Comment by lostanlen** [comment]
Since we still have an skcuda backend, then maybe this (post-#972) is working as intended? @janden 
We have contiguous tensors all the way

**Comment by janden** [comment]
We should come back to this once we have removed skcuda. But for now, we'll need the clone introduced in #972. Removing the 0.4 milestone for now.
